WARRIOR_HP = 150
WARRIOR_WEAPON_DAMAGE = 20
WARRIOR_WEAPON_HIT_CHANCE = 0.9
WARRIOR_WEAPON_DURABILITY = 25

MAGE_HP = 130
MAGE_MANA = 100
MAGE_WEAPON_DAMAGE = 25
MAGE_WEAPON_HIT_CHANCE = 0.7
MAGE_WEAPON_DURABILITY = 50
MAGE_SPELL_COST = 10